name: STM32 CI
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    container: niuslar/stm32_headless_build:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: |
          cd /opt/st/stm32cubeide_1.8.0
          ./headless-build.sh -data /workspace -import /__w/actions_pi/actions_pi -cleanBuild 'HIL_Example' -markerType cdt || { echo "Build Failed"; exit 1; }
      - uses: actions/upload-artifact@v3
        with:
          name: release_build
          path: /__w/actions_pi/actions_pi/Debug/HIL_Example.bin

  flash_release:
    runs-on: self-hosted
    needs: build
    steps: 
      - name: Download Release Build    
        uses: actions/download-artifact@v3
        with: 
          name: release_build 
      - name: Download Flash Script
        run: | 
          wget https://raw.githubusercontent.com/Niuslar/stm32f411_flash/main/stm32_flash_loader.py 
      - name: Flash STM32 board
        run: |
          python3 stm32_flash_loader.py HIL_Example.bin
          rm HIL_Example.bin stm32_flash_loader.py
