name: STM32 CI
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    container: niuslar/stm32-cubeide-headless:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: |
          chmod +x /opt/st/stm32cubeide_1.9.0/headless-build.sh
          cd /opt/st/stm32cubeide_1.9.0
          ./headless-build.sh -data /workspace -import /__w/actions_pi/actions_pi -cleanBuild 'HIL_Example' -markerType cdt || { echo "Build Failed"; exit 1; }
      - uses: actions/upload-artifact@v3
        with:
          name: build_artifact
          path: /__w/actions_pi/actions_pi/Release/HIL_Example.bin

flash_release:
  runs-on: self-hosted
  needs: build
  steps: 
    - name: Download Release Build    
      uses: actions/download-artifact@v3
      with: 
      name: release_build  # This is the name we gave the build artifact before
    - shell: bash
      run: | # This is to run multiple lines of commands 
        wget https://raw.githubusercontent.com/Niuslar/stm32f411_flash/main/stm32_flash_loader.py 
        stm32_flash_loader.py HIL_Example.bin
        rm HIL_Example.bin stm32_flash_loader.py
